[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
