[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# to write to addresses.json
fs_permissions = [
  {  access = "read-write", path = "./addresses.json"},
  {  access = "read-write", path = "./test/json"},
  {  access = "read-write", path = "./out"}]

[rpc_endpoints]
sepolia = "https://rpc.ankr.com/eth_sepolia"